### ISSUE TITLE
An example without referring to dist directory 

### ISSUE THREAD

**Issue by muke5hy** [mwood23/preact-island#5]
It would be great to have an example without importing anything from the dist folder. 

Currently the following line is being imported in `example/src/call-to-action.island.tsx` file 

```import { createIsland } from '../../dist/index.module' ```

**Comment by mwood23** [comment]
@muke5hy I don't want to alter the example folder to rely on the package from NPM because it's valuable for development and it allows folks to log around the code to see how it works easily. However, it is a good amount of leg work in order to get going with the repo so I've built a starter that bootstraps a zero config multi island project.

This should have everything you need to get started! 🚀 

https://github.com/mwood23/preact-island-starter
